CORE-4026/retrain on next set of data
Unstructured-IO/super-gradients-fork pull request #25
Opened 2024-03-07 09:38 UTC by mariannaparzych

To download all data from S3:
```
python helper_scripts/download_new_data_and_convert_to_coco_format.py --images_dir /path/to/images/ --labels_path /path/to/annotations/之前数据2k返修.txt /path/to/annotations/之前数据重标4633.txt /path/to/annotations/TOcs.txt /path/to/annotations//patents.txt /path/to/annotations/forms.txt /path/to/annotations/second_document_chest_batch1+(12095).csv
--existing_coco_labels_dir /path/to/existing/COCO/splits/dir/ --existing_categories_file /path/to/classnames.txt --coco_labels_dir /path/to/data/dir/COCO/ --download_images --only_split_existing_COCO
```
To train:
`modal run src/super_gradients/train_from_recipe_modal.py --config-name train_unstructured_feb24_yolox.yaml`

2024-03-07 09:52 UTC, mariannaparzych commented
Some changes are only formatting due to the `pre-commit`

2024-03-07 11:30 UTC, amaciaszek-dsai requested changes
minor remarks

2024-03-07 11:30 UTC, amaciaszek-dsai commented on src/super_gradients/recipes/train_unstructured_feb24_yolox.yaml
> +experiment_name: CORE-4026_retrain_on_next_set_of_data
leftover

2024-03-07 11:30 UTC, amaciaszek-dsai commented on src/super_gradients/recipes/train_unstructured_feb24_yolox.yaml
> +    tags: ["CORE-4026", "object detection", "training", "unstructured_feb24_4", "data 20K"]
leftover

2024-03-07 11:30 UTC, amaciaszek-dsai commented on unstructured_scripts/download_new_data_and_convert_to_coco_format.py
> +        category["name"] = clean_category_name(category["name"])
don't we want to keep that sorted?

2024-03-07 13:04 UTC, mariannaparzych commented on unstructured_scripts/download_new_data_and_convert_to_coco_format.py
> +        category["name"] = clean_category_name(category["name"])
it is sorted by "id" by default - bc of the way it is initialized, this sorting was a leftover after some manipulations that are gone now. however I can keep this sorting "just in case"

2024-03-11 14:46 UTC, amaciaszek-dsai approved these changes
LGTM

2024-03-11 16:20 UTC, merged