unstructured inference refactoring
Unstructured-IO/super-gradients-fork pull request #30
Opened 2024-03-14 08:44 UTC by amaciaszek-dsai

2024-03-14 09:45 UTC, mariannaparzych commented on unstructured_sg/mappings.py
> +DOCLAYNET_CAT = [
z czystej ciekawości "unstructured_sg" to ?

2024-03-14 09:45 UTC, mariannaparzych commented on unstructured_sg/scripts/unstructured_predict.py
> +    parser.add_argument(
Since, as I assume, this script will be used by people outside OD team, maybe some comment on what this file is, and why it is not necessary to use while testing random documents?

2024-03-14 09:45 UTC, mariannaparzych commented on unstructured_sg/scripts/unstructured_predict.py
> +import argparse
There is no example command for this script

2024-03-14 10:08 UTC, amaciaszek-dsai commented on unstructured_sg/mappings.py
> +DOCLAYNET_CAT = [
super-gradients. W libce czasami używają takiego skrótu. Na początku wrzuciłem jako `unstructured`, ale potem miałem `from unstructured import ...` co wygląda jakbym importowałem z oficjalnej libki unstructured

2024-03-15 14:17 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/unstructured_predict.py
> +import argparse
Done!

2024-03-15 14:17 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/unstructured_predict.py
> +        "--model_name",
Done!

2024-03-15 14:18 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/unstructured_predict.py
> +    parser.add_argument(
Done!

2024-03-15 16:16 UTC, amaciaszek-dsai commented on unstructured_sg/README.md
> +    6. Now you can run inference using `unstructured_sg/scripts/unstructured_predict.py --model_name <new_model_name> ...` script.
I moved that to a separate number 10. 

Instead of highlighting - I moved `## Running inference (simple usage for users out of DS team)` section above the workflow so that it's more visible for outside users :)

2024-03-18 09:54 UTC, mariannaparzych requested changes

2024-03-18 09:54 UTC, mariannaparzych commented on unstructured_sg/scripts/unstructured_predict.py
> +from unstructured_sg.model_configs import MODEL_CONFIGS
I got :
```
Exception has occurred: ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
No module named 'unstructured_sg'
```

2024-03-18 10:26 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/unstructured_predict.py
> +from unstructured_sg.model_configs import MODEL_CONFIGS
Done! :)

2024-03-18 10:30 UTC, mariannaparzych approved these changes

2024-03-18 10:34 UTC, merged