CORE-4281 - onnx conversion
Unstructured-IO/super-gradients-fork pull request #35
Opened 2024-03-21 12:23 UTC by amaciaszek-dsai

ONNX conversion:
    1. To convert model to ONNX format, you can use `unstructured_sg/scripts/onnx_export.py` script.
    e.g.: `PYTHONPATH=. python unstructured_sg/scripts/onnx_export.py --model_name yolox_mar24_3_1 --output_path .`
    2. Upload ONNX model to huggingface unstructured-io organization.
    3. Add model config into `unstructured_sg/model_configs.py`
 
You can run inference on ONNX model using `unstructured_sg/scripts/onnx_predict.py --model_name <new_model_name> ...` script.
e.g:
`PYTHONPATH=. unstructured_sg/scripts/onnx_predict.py --model_name yolox_mar24_3_1 --input_dir <INPUT_DIR> --output_dir <OUTPUT_DIR>`

2024-03-21 14:48 UTC, mariannaparzych requested changes

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/README.md
> +12. Now you can run inference on ONNX model using `unstructured_sg/scripts/onnx_predict.py --model_name <new_model_name> ...` script.
shouldn't this be also presented more clearly, outside of theese steps, so people outside the OD team can easily test it?

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/model_configs.py
> +UnstructuredYoloXMAR24_1_1_OnnxConfig = UnstructuredODModelConfigOnnx(
IMO numbers of ONNX versions should be same, as .pth checkooint versions used to prepare this onnx. Is it prepared like that or differently?

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/utils/file.py
I don't know if this is the best name, I was bit confused with importing `from unstructured_sg.utils.file`. Maybe smth like io_utils.py ?

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/utils/inference.py
> +def save_json_output(image_detection_prediction: ImageDetectionPrediction, output_path: Path):
this is not just saving anythng into json, thid expects specyfic ImageDetectionPrediction as input and formats it in defined way, I think it should be called smth like save_detection_prediction_to_json, so it is obvious for everybody, what does this fnc do

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/utils/inference.py
> +def get_layout_elements_from_prediction(image_prediction: ImageDetectionPrediction) -> list[LayoutElement]:
where is this func used?

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/utils/inference.py
IMO to consider if this file is needed? don't know where get_layout_elements_from_prediction is used, if it is specific for some single script maybe it should stay there? save_json_output is bit more specific to prediction scripts, but load_images seems quite generic, and might be with other io funcs?

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/scripts/onnx_export.py
> +@click.command()
maybe add TODOs next to argparses in other unstructured_sg scripts? It would be good to make it consistent, and I agree click is nice :)

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/scripts/onnx_export.py
> +    checkpoint_path = hf_hub_download(repo_id=model_config.checkpoint_repo_id,
it is impossible to converts local, "unregistered" checkpoint from local path? It makes sense, but maybe add some docstring to file, so it explained

2024-03-21 14:48 UTC, mariannaparzych commented on unstructured_sg/scripts/onnx_predict.py
> +from super_gradients.training.utils.predict import DetectionPrediction, ImageDetectionPrediction
I think this should be in the end free from supergradients dependeciens - It is work for another task, but maybe lets add TODOs for future

2024-03-21 23:17 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/onnx_predict.py
> +from super_gradients.training.utils.predict import DetectionPrediction, ImageDetectionPrediction
Initially it was also my idea, but when I worked on that I decided that these dependencies are quite useful as they provide the same interfaces as in _unstructured_predict.py_. E.g. we can generate visualizations in the same way. In my temporary work I was using some other function but this way visualizations looked differently than what we got used to. Additionally to make it free from super-gradients we'd need to drop this from config:
`    processings=[DetectionLongestMaxSizeRescale((640, 640)), DetectionBottomRightPadding((640, 640), 114), ImagePermute((2, 0, 1))]` and use pure numpy functions. I think current way is quite nice and clean.

I think it will be good enough to have dependency-free version in inference / core repository

2024-03-21 23:17 UTC, amaciaszek-dsai commented on unstructured_sg/utils/inference.py
`get_layout_elements_from_prediction` is used in `save_json_output` aka `save_detection_prediction_to_json`. And this `save_detection_prediction_to_json` is shared in _onnx_predict.py_ and _unstructured_predict.py_. Additionally,  _visualize_and_save_results..._ can potentially use some code from this file.

When it comes to `load_images` I don't have strong preferences, on one hand it's actually some IO operation, on the other it's a bit more specific, with more specific library dependencies, and probably more joined with inference. But _io.py_ is probably also good place. What do you like more?

2024-03-22 10:00 UTC, amaciaszek-dsai commented on unstructured_sg/README.md
> +12. Now you can run inference on ONNX model using `unstructured_sg/scripts/onnx_predict.py --model_name <new_model_name> ...` script.
Done

2024-03-22 10:00 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/onnx_export.py
> +@click.command()
Done

2024-03-22 10:26 UTC, mariannaparzych commented on unstructured_sg/utils/inference.py
well, after you explained, I also believe both are fine

2024-03-22 10:28 UTC, mariannaparzych commented on unstructured_sg/utils/inference.py
> +def load_images(file_path):
now I think, maybe lets call it `load_document`? bc it loads signle image, or converts pdf to multiple images, and when I seen `load_images` I think I can use it to bulk load many images from disc.

2024-03-22 10:35 UTC, amaciaszek-dsai commented on unstructured_sg/utils/inference.py
> +def load_images(file_path):
Yup, good point. I also modified docstr a bit and added type hints for better self-documentation

2024-03-22 10:37 UTC, mariannaparzych commented on unstructured_sg/scripts/onnx_export.py
> +    output_name = str(output_path / f"{model_name}.onnx")
```
File "/home/marianna.parzych/Unstructured/super-gradients-fork/unstructured_sg/scripts/onnx_export.py", line 42, in export_onnx
    output_name = str(output_path / f"{model_name}.onnx")
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

2024-03-22 10:55 UTC, amaciaszek-dsai commented on unstructured_sg/scripts/onnx_export.py
> +    output_name = str(output_path / f"{model_name}.onnx")
fix'd

2024-03-22 12:46 UTC, mariannaparzych approved these changes

2024-03-22 12:47 UTC, merged